---
title: "WILD 7970 Assignment 1"
author: "Basanta Shrestha"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

<span style="color:red">Just a couple of quick notes about how R Markdown works. Any text (such as your journal responses, can be typed right here. You had them inserted as R code chunks previously because you had them within sections that started with "{r}". You only need to put R code in a section like that. In addition, I've changed the name of your document to "Journal.Rmd." In the future, just continue adding your responses to each week's discussion in this same document. - Jonathon</span>


# Assignment 1: summary of paper "ChatGPT: five priorities for research"

summary: "OpenAI's ChatGPT, a powerful AI tool, is revolutionizing research with its content creation capabilities. Researchers now harness it for tasks from essay writing to potentially aiding editorial decisions. However, its prowess isn't without pitfalls. The model can sometimes produce misleading content, posing risks of misinformation in scientific circles. There's also a gray area regarding potential unintentional plagiarism and authorship concerns with AI-generated content. For me, the growing use of AI tools like ChatGPT in scientific endeavors underscores the importance of transparency. Who really owns AI-generated content, and how do we handle authorship? As AI blurs these lines, it's essential for the scientific community to establish clear guidelines. Moreover, with AI giants like OpenAI often keeping their tech proprietary, I'm intrigued by pushes for open-source AI, which might democratize and clarify AI's role in research.As AI reshapes academia, we must balance innovation with ensuring the integrity and authenticity of our work. The essence of research—curiosity and discovery—should always remain at its core."

<span style="color:red">Good summary. AI is exciting and scary at the same time. One of the things we talked about in class was whether there are core parts of the scientific process that need to remain in the hands of the scientist and that should never be outsourced to a machine. If the answer is "nothing" then what do we need scientists for? Just some food for thought. - Jonathon</span>

<mark> You can separate your weekly summaries by typing three dashes as shown below. Ani

---


# Assignment 2:

<span style="color:red">Go ahead and type your response to Assignment 2 right here and keep adding to your journal each week.</span>
summary: "In my opinion, Faculty hiring hasn't always been fair. In the past, many groups like LGBTQ+, Black, Hispanic, and Indigenous people often got left out. This isn't just bad for them; it also slows down our scientific progress and makes things unequal. Before we even start hiring, we need to make sure our departments are welcoming for everyone. Using clear guidelines and rules can help everyone get a fair chance during hiring. It's also super important to be clear and fair when we're interviewing people and offering them jobs. If we're serious about making our teams diverse, we need to fix any unfair practices and make sure everyone knows what's expected. This way, we can make sure our faculty represents all parts of our community."

# Assignment 3: Summary of Reproducibility

summary: "Although the term "reproducibility" was new to me, I've already encountered some of the challenges it represents during my grad school research. Human tendencies, like seeing patterns where none exist, can misguide results. Such biases sometimes lead researchers to either myopic focuses or data manipulation. Andrew Gelman's 2013 paper and the wrongful conviction of Sally Clark serve as cautionary tales. However, innovative methods, like "Blind Data Analysis" in physics, promise more accurate and bias-free outcomes, adding a layer of excitement and confidence to the scientific process."

<mark> Glad you learned something new! - Jonathon

# Assignment 4: Funding Bias
summary: "In my opinion, We need to dig deeper into the methods and outcomes. It's crucial that we, as researchers, don't jump to conclusions and stay open to other explanations. In summation, while biases and conflicts of interest might be intertwined with research, they don't necessarily denote the absolute truth. Often, the crux of the matter is nestled between two extremes. The solution might lie in marrying pre-established research objectives with adaptive methodologies. Accepting the existence of biases yet continually striving to curb their negative implications is our way forward in the scientific realm."

<span style="color:red">So true. Bias isn't going away, so we need to figure out how to live with it ethically and productively. - Jonathon</span>

# Assignment 5: Citizen Science
Summary: "In my opinion, citizen science is transformative, especially in ecological and environmental research. I admire how the paper illustrates its entire journey, from inception to ethical data management. Its diverse applications, from biodiversity to marine pollution, are truly commendable. Despite its undeniable potential, addressing challenges is crucial for its wider adoption."

<span style="color:red">Agreed. I was playing devil's advocate a bit in class today, but I think there is a lot of valuable uses for citizen science data. We just need to make sure to recognize it is no silver bullet for answering all of our research questions. - Jonathon</span>

# Assignment 6: Hypotheses reading
Summary: "From the paper, I've learned that the use of hypotheses in ecological and evolutionary research has been surprisingly stagnant over the past 25 years, despite their historical significance in fostering discovery and mitigating bias. While the digital age and the emergence of predictive models cast doubts on the current relevance of hypotheses, their limited presence in eco-evo research raises questions. Notably, funding or citation metrics don't seem to favor hypothesis-driven work. Yet, the authors emphasize the unparalleled clarity, precision, and depth that multiple alternative hypotheses can introduce to research, urging for a reevaluation of their importance, which I completely agree."

<span style="color:red">Perhaps good ideas are good ideas whether they are clearly stated as hypotheses or not? - Jonathon</span>

# Assignment 7: Predatory Journals
Summary: "At this point, it’s clear that predatory journals exist, and their prevalence is increasing day by day. However, there is significant confusion regarding the definition of predatory journals and determining which ones are predatory and which are not. There is an urgent need to control or eliminate predatory journals, but there seems to be no consensus among scholars and the scientific community on how to achieve this. I have prepared a presentation with some relevant materials, and I hope we will have a productive discussion about this issue in class."

<span style="color:red">We did indeed. Defining a predatory journal is the real sticky point for me. How do you distinguish between a journal that is ill-intentioned vs. one that is just kind of figuring out the process? - Jonathon</span>

# Assignment 8: Pre-Registration:
Summary: "The paper reveals the positive effects of preregistration in social and behavioural sciences, emphasizing its role in reducing confirmation bias by clarifying research plans in advance. Those with experience in preregistration often find it improves the overall quality of research, aiding in hypothesis formation, design, and analysis. The survey also indicates that preregistration enhances preparation and
collaboration among research teams, contributing to a more structured and reliable research process. However, despite these benefits, I think there are notable drawbacks. Preregistration can limit flexibility and
discourage the exploration of new ideas during research. It may also introduce added complexities, making the process challenging, particularly for newcomers. But in my opinion, the major concern is, it could lead to a narrow focus on testing hypotheses, overshadowing the development of broader theories and limiting the applicability of the research in various contexts, suggesting a need for a more balanced and adaptable approach."

<span style="color:red">Yes, this was the general consensus in class. The inflexibility of the approach, coupled with the increased review time, seems to scare a lot of folks. Note that you will only receive half credit for this entry given you were not in class today. - Jonathon</span>

# Assignment: Blind Peer Reviews: 
Summary: "The study discussed the influence of author prominence on peer review outcomes. While more than 3300 researchers were involved and 534 review reports were analyzed for study purposes (called to review papers co-authored by researchers with different statuses), a significant status bias was observed during the study. The bias was attributed to the so-called 'halo effect', where reviewers unconsciously ascribe higher quality to the works of renowned researchers. The study suggests further exploration of alternative review processes, such as transparent or structured peer reviews, to gain deeper insights into bias in manuscript assessment, which I totally agree. A double anonymized review process can be one of the effective solutions for this issue going forward in my opinion."

<span style="color:red">Agreed. - Jonathon</span>


# Assignment: Science Communication
Summary: "The paper emphasized the importance of science communication skills in enhancing presentation capabilities and networking for early-career researchers. It noted that clarity on experimental practices, particularly in animal studies, could alleviate public doubts. The journey to science communication may start with volunteer work. In our class discussions on the role of social media in science communication, I reserved some skepticism about sharing intricate research details with the general public, as not all procedures and nuanced data may be pertinent or comprehensible to them. While certain research steps essential to our work might not always be well-received, they remain crucial, and we should navigate public opinion carefully. Nevertheless, it’s important to engage with the public on scientific matters that are beneficial for broader understanding."

<span style="color:red">Yes, it's very difficult to figure out how to walk this fine line. - Jonathon</span>

#Assignment: Mental Health in Academia
Summary: "The paper highlights a critical mental health crisis among graduate students globally, with significant rates of depression and anxiety. Key findings include that 43-46% of bioscience graduate students at UC Berkeley and a majority at the University of Arizona reported high levels of stress. A comprehensive survey of 2,279 graduate students from 26 countries revealed that 41% experienced moderate to severe anxiety and 39% moderate to severe depression, rates significantly higher than the general population, which did not surprise me at all. The research also uncovered that transgender/gender-nonconforming and female students faced higher risks, with 55% and 57% respectively suffering from anxiety and depression. The study underscores the urgent need for academia and policymakers to implement effective mental health strategies and intervention programs, emphasizing the importance of mentorship quality, work-life balance, and a supportive academic culture. I agree with the conclusion of the paper as addressing mental health issues of graduate students is fundamental to the success of those students and Universities as well."
